- name: "SIGNAL | Adding signing key"
  become: true
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc

- name: "SIGNAL | Adding repo"
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    update_cache: true
    filename: signal

- name: "SIGNAL | Installing package"
  become: true
  apt:
    name: signal-desktop