- name: "GIT | Create bitbucket ssh directory"
  file:
    path: "{{ ansible_env.HOME }}/.ssh/bitbucket"
    state: directory

- name: "GIT | Install bitbucket ssh keys"
  become: true
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/bitbucket/{{ item.file }}"
    content: "{{ item.content }}"
    mode: u=rw,g=,o=
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - file: id_rsa
      content: "{{ bitbucket_ssh.private }}"
    - file: id_rsa.pub
      content: "{{ bitbucket_ssh.public }}"

- name: "GIT | Updating ssh config to use bitbucket keys"
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    create: true
    block: |
      Host bitbucket.org
          IdentityFile {{ ansible_env.HOME }}/.ssh/bitbucket/id_rsa
          AddKeysToAgent yes
    marker: "# {mark} ANSIBLE: bitbucket"