- name: "GIT | Applying useful git configurations"
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
  - name: user.name
    value: "{{ git_config.name }}"

  - name: user.email
    value: "{{ git_config.email }}"

  - name: github.user
    value: "{{ github_config.user }}"

  - name: github.token
    value: "{{ github_config.token }}"

  - name: push.followTags
    value: true

  - name: push.default
    value: simple

  - name: core.fileMode
    value: false

  - name: color.ui
    value: true

  - name: format.pretty
    value: online

  - name: alias.co
    value: checkout

  - name: alias.s
    value: status

  - name: alias.d
    value: diff

  - name: alias.cm
    value: commit -m

  - name: alias.ca
    value: commit -am

  - name: alias.pl
    value: pull

  - name: alias.pu
    value: push

  - name: alias.a
    value: add

  - name: alias.l
    value: log --oneline -n20

  - name: alias.aa
    value: commit --amend

  - name: alias.sb
    value: show-branch

  - name: alias.subdate
    value: '"!git submodule update --init --recursive"'

  - name: alias.mote
    value: '"!git fetch --all && git show-branch $$(git rev-parse --abbrev-ref HEAD) origin/$$(git rev-parse --abbrev-ref HEAD)"'
