- name: "GIT | Create github ssh directory"
  file:
    path: "{{ ansible_env.HOME }}/.ssh/github"
    state: directory

- name: "GIT | Install github ssh keys"
  become: true
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/github/{{ item.file }}"
    content: "{{ item.content }}"
    mode: u=rw,g=,o=
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - file: id_rsa
      content: "{{ github_ssh.private }}"
    - file: id_rsa.pub
      content: "{{ github_ssh.public }}"

- name: "GIT | Updating ssh config to use github keys"
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    create: true
    block: |
      Host github.com
          IdentityFile {{ ansible_env.HOME }}/.ssh/github/id_rsa
    marker: "# {mark} ANSIBLE: github"