- name: "GIT | Create gitlab ssh directory"
  file:
    path: "{{ ansible_env.HOME }}/.ssh/gitlab"
    state: directory

- name: "GIT | Install gitlab ssh keys"
  become: true
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/gitlab/{{ item.file }}"
    content: "{{ item.content }}"
    mode: u=rw,g=,o=
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - file: id_rsa
      content: "{{ gitlab_ssh.private }}"
    - file: id_rsa.pub
      content: "{{ gitlab_ssh.public }}"

- name: "GIT | Updating ssh config to use gitlab keys"
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    create: true
    block: |
      Host gitlab.com
          IdentityFile {{ ansible_env.HOME }}/.ssh/gitlab/id_rsa
          AddKeysToAgent yes
    marker: "# {mark} ANSIBLE: gitlab"