- name: "SYSTEM76 | Adding apt repo"
  become: true
  apt_repository:
    repo: ppa:system76-dev/stable
    update_cache: true

- name: "SYSTEM76 | Installing packages"
  apt:
    name: "{{ item }}"
  with_items:
    - system76-driver
    - system76-driver-nvidia

- name: "SYSTEM76 | Update grub nomodeset"
  become: true
  lineinfile:
    regexp: '^GRUB_CMDLINE_LINUX='
    line: GRUB_CMDLINE_LINUX=””
    dest: /etc/default/grub
  register: grubfix

- name: "SYSTEM76 | Update grub"
  become: true
  command: "update-grub"
  when: grubfix.changed
