terminal_default_profile: e83a0879-55a8-457a-8ff8-1c6e16e6456c
terminal_profiles_list: "['e83a0879-55a8-457a-8ff8-1c6e16e6456c', '01d81b02-4e2d-418b-af8a-d82db5437ccd']"
terminal_profiles:
- uuid: e83a0879-55a8-457a-8ff8-1c6e16e6456c
  settings:
  - key: visible-name
    value: "'Basic'"
  - key: use-system-font
    value: "false"
  - key: font
    value: "'Ubuntu Mono 12'"
  - key: use-theme-transparency
    value: "false"
  - key: use-theme-colors
    value: "true"
- uuid: 01d81b02-4e2d-418b-af8a-d82db5437ccd
  settings:
  - key: visible-name
    value: "'Vagrant'"
  - key: use-system-font
    value: "false"
  - key: font
    value: "'Ubuntu Mono 12'"
  - key: use-theme-transparency
    value: "false"
  - key: use-theme-colors
    value: "false"
  - key: background-color
    value: "'rgb(0,43,54)'"
  - key: foreground-color
    value: "'rgb(131,148,150)'"
terminal_keybindings:
- key: new-window
  value: "'<Primary>n'"
- key: new-tab
  value: "'<Primary>t'"
- key: close-tab
  value: "'<Primary>w'"
- key: close-window
  value: "'<Primary>q'"