- name: "Adding system76 apt repo"
  become: true
  apt_repository:
    repo: ppa:system76-dev/stable

- name: "Apt Update"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: full

- name: "Install basic packages"
  become: true
  apt: 
    name: "{{ item }}"
  with_items:
    - vim
    - system76-driver
