- name: "THUNDERBIRD | Creating directory for Thunderbird"
  file:
    path: "{{ ansible_env.HOME }}/Applications/thunderbird"
    state: directory

- name: "THUNDERBIRD | Determining latest release URL"
  script: latest.sh
  register: thunderbird_release

- name: "THUNDERBIRD | Downloading Thunderbird"
  get_url:
    url: "{{ thunderbird_release.stdout_lines.0 }}"
    dest: "{{ ansible_env.HOME }}/Applications/thunderbird"
    timeout: 45
  register: thunderbird_bundle

- name: "THUNDERBIRD | Unpacking bundle"
  unarchive:
    src: "{{ thunderbird_bundle.dest }}"
    dest: "{{ ansible_env.HOME }}/Applications/thunderbird"
    remote_src: true

- name: "THUNDERBIRD | Cleaning up bundle"
  file:
    path: "{{ thunderbird_bundle.dest }}"
    state: absent

# This is ideal, but will timeout  -- https://github.com/ansible/ansible/issues/23864
#- name: "THUNDERBIRD | Downloading Thunderbird"
#  unarchive:
#    src: "{{ thunderbird_release.stdout_lines.0 }}"
#    dest: "{{ ansible_env.HOME }}/Applications/thunderbird"
#    remote_src: true

- name: "THUNDERBIRD | Getting latest version (kinda)"
  command: bash -c "ls -lt {{ ansible_env.HOME }}/Applications/thunderbird | grep -v '^total' | head -n1 | awk '{printf $9}'"
  register: thunderbird_latest_download

- set_fact:
    thunderbird_location: "{{ ansible_env.HOME }}/Applications/thunderbird/{{ thunderbird_latest_download.stdout }}"

- name: "THUNDERBIRD | Creating desktop file for thunderbird app"
  become: true
  template:
    src: entry.desktop
    dest: /usr/share/applications/thunderbird.desktop
