- name: "INTELLIJ | Creating directory for IntelliJ"
  file:
    path: "{{ ansible_env.HOME }}/Applications/intellij"
    state: directory

- name: "INTELLIJ | Downloading Intellij Ultimate"
  unarchive:
    src: https://download.jetbrains.com/idea/ideaIU-2017.2.5.tar.gz
    dest: "{{ ansible_env.HOME }}/Applications/intellij"
    remote_src: true

- name: "INTELLIJ | Getting latest version (kinda)"
  command: bash -c "ls -lt {{ ansible_env.HOME }}/Applications/intellij | tail -n1 | awk '{printf $9}'"
  register: intellij_latest_download

- set_fact:
    intellij_location: "{{ ansible_env.HOME }}/Applications/intellij/{{ intellij_latest_download.stdout }}"

- name: "INTELLIJ | Creating desktop file for intellij app"
  template:
    src: entry.desktop
    dest: /usr/share/applications/intellij.desktop
  become: true