- name: "KUBERNETES | Install required packages"
  become: true
  apt:
    name: apt-transport-https

- name: "KUBERNETES | Adding signing key: kubectl"
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: "KUBERNETES | Adding repo: kubectl"
  become: true
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    update_cache: true
    filename: kubernetes

- name: "KUBERNETES | Installing kubectl"
  become: true
  apt:
    name: kubectl

- name: "KUBERNETES | Getting latest minikube release"
  script: latest-minikube.sh
  register: minikube_release

- name: "KUBERNETES | Downloading latest minikube"
  become: true
  get_url:
    url: "{{ minikube_release.stdout_lines.0 }}"
    dest: /usr/local/bin/minikube
    mode: u+x,o+x,g+x