- name: "SSH | Create github ssh directory"
  file: 
    path: "{{ ansible_env.HOME }}/.ssh/github"
    state: directory

- name: "SSH | Install github ssh keys"
  become: true
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/github/{{ item.file }}"
    content: "{{ item.content }}"
    mode: u=rw,g=,o=
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items: 
    - file: id_rsa
      content: "{{ ssh_private_key }}"
    - file: id_rsa.pub
      content: "{{ ssh_public_key }}"

 - name: "SSH | Updating ssh config to use github keys"
   blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    create: true
    block: |
      Host github.com
          IdentityFile {{ ansible_env.HOME }}/.ssh/github/id_rsa  
    marker: "# {mark} ANSIBLE: github"


