- name: "TELEGRAM | Creating directory for Telegram"
  file:
    path: "{{ ansible_env.HOME }}/Applications/telegram"
    state: directory

- name: "TELEGRAM | Downloading bundle"
  unarchive:
    src: "https://telegram.org/dl/desktop/linux"
    dest: "{{ ansible_env.HOME }}/Applications/telegram"
    remote_src: true

- name: "TELEGRAM | Copying over telegram logo"
  copy:
    src: logo.png
    dest: "{{ ansible_env.HOME }}/Applications/telegram/logo.png"

- set_fact:
    telegram_location: "{{ ansible_env.HOME }}/Applications/telegram"

- name: "TELEGRAM | Creating desktop file for telegram app"
  become: true
  template:
    src: entry.desktop
    dest: /usr/share/applications/telegram.desktop