- name: "NODEJS | Adding apt key"
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: "NODEJS | Adding apt repo"
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main
    update_cache: true
    filename: nodejs

- name: "NODEJS | Installing packages"
  become: true
  apt:
    name: "{{ item }}"
  with_items:
  - apt-transport-https
  - nodejs