- name: "SPOTIFY | Adding signing key"
  become: true
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "{{ item }}"
  with_items:
  - BBEBDCB318AD50EC6865090613B00F1FD2C19886
  - 0DF731E45CE24F27EEEB1450EFDC8610341D9410

- name: "SPOTIFY | Adding repo"
  become: true
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    update_cache: true

- name: "SPOTIFY | Installing package"
  become: true
  apt:
    name: spotify-client