- name: "SPOTIFY | Adding signing key"
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg

- name: "SPOTIFY | Adding repo"
  become: true
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    update_cache: true
    filename: spotify

- name: "SPOTIFY | Installing package"
  become: true
  apt:
    name: spotify-client